version: "3.9"
services:
  php:
    container_name: php
    restart: always
    ports:
      - "0.0.0.0:3939:80"
    build: 
      context: ../
      dockerfile: ./docker/php.Dockerfile
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'appleid_auto'


    volumes:
      - ../db/mysql:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d/
      - ./:/data/
networks:
  default:
    driver: bridge


